name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Hostinger via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # necesario para git-ftp (diff con commit anterior)

      - name: Deploy con git-ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: vivaaustralia.com.au
          username: u905238757.vivaaustralia.com.au
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          server-dir: /public_html/wp-content/plugins/viva-pre-evm/
          local-dir: ./
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
